[general]
shuffle_caption = true
caption_extension = '.txt'


[[datasets]]
resolution = [1024,1024]
batch_size = 1


[[datasets.subsets]]
        image_dir = "newstuff/pics/white-chair_denoised"
        class_tokens = "xyrc chair"
        num_repeats = 10

